# Generated by Django 4.2.11 on 2026-02-27 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interrogations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interrogation',
            name='captain_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_interrogation_decisions', to=settings.AUTH_USER_MODEL),
        ),
    ]
